### ISSUE TITLE
Solutions containing cyrillic (non-latin?) characters do not appear in the assessed solutions list.

### ISSUE THREAD

**Issue by Nadare2012** [aws/porting-assistant-dotnet-datastore#6]
Solutions containing cyrillic (non-latin?) characters do not appear in the assessed solutions list. Re-adding solution is not possible, "Solution file already exists".

Steps to reproduce:
1. Download solution below:
[Кириллица.zip](https://github.com/aws/porting-assistant-dotnet-datastore/files/5150468/default.zip)
2. Add a solution.

**Comment by mhwkanon** [comment]
Hi @Nadare2012, thank you fo reporting the issue. We can fix it in the next release on 9/30. I'll keep you updated.

**Comment by mrlloyd-amzn** [comment]
This is fixed.
